### Indexar snippet com ES
POST http://localhost:3000/snippets
Content-Type: application/json

{
  "id": "es-test-1",
  "content": "console.log('hello elastic')",
  "language": "javascript"
}

### Buscar snippet
GET http://localhost:3000/snippets/search?q=elastic
